### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by leovarmak** [t7hm1/pyddos#1]
![image](https://user-images.githubusercontent.com/14135553/29003550-7219c894-7ad6-11e7-928f-dd3baebfff32.png)

**Comment by smithHK** [comment]
online 405 replace this line
from
**for x in xrange(0,args.T):**
to 
**for x in xrange(0,int(args.T)):**
it`s work for me.

**Comment by scriptzteam** [comment]
Traceback (most recent call last):
  File "pyddos.py", line 444, in <module>
    main()
  File "pyddos.py", line 416, in main
    for x in xrange(int(args.T)):
NameError: name 'xrange' is not defined
root@xxx:~/pyddos# nano pyddos.py

**Comment by saaaami** [comment]
**`xrange replace to range is worked`**
